name: GeneratePDF

on:
  repository_dispatch:
    types: [trigger-generate-pdf-workflow]

jobs:
  generatePdf:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js v15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Generate PDF Action
        uses: ashuvssut/generatePdf-GHA@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
